### ISSUE TITLE
Regarding value in ReLU

### ISSUE THREAD

**Issue by chanfm81** [qianlou/SHE#2]
Hi,

When i edit line 119 in https://github.com/qianlou/SHE/blob/master/src/SHE.cpp to "0", the value of "Max_plain_result" variable is still -4. Any idea?

Thanks.

**Comment by qianlou** [comment]
Hi,

Thanks very much for your interests on our project. Please check the latest codes. You will get the following result:
![Screenshot from 2020-03-12 17-37-04](https://user-images.githubusercontent.com/31481607/76568930-4be74900-6488-11ea-835e-170c4cbf48d2.png)

Bests,
~Qian

**Comment by chanfm81** [comment]
Hi,

The ReLU is working fine now.

Thanks.
