### ISSUE TITLE
Regarding ShiftDotProduct

### ISSUE THREAD

**Issue by chanfm81** [qianlou/SHE#3]
Hi,

When i edit line 93 of https://github.com/qianlou/SHE/blob/master/src/SHE.cpp to -1, below is the difference in result between plain and decrypted:
Decrypted Result:16
Result:0

Any idea?

Thanks.

**Comment by qianlou** [comment]
Hi,

Thanks very much for your interests on our project. Please check the latest codes. You will get the following result:
![Screenshot from 2020-03-12 17-37-04](https://user-images.githubusercontent.com/31481607/76569045-92d53e80-6488-11ea-88cb-961ec3b62a7a.png)

Bests,
~Qian

**Comment by chanfm81** [comment]
Hi,

Thanks for the speedy response. 
When i tried Be=[ 0 0 0 0 0 0 0 0] , the decrypted result is not same as plain result:
######## 1. shiftDot(A[0:input_size-1], Be[0:input_size-1]) Verification#######
A=[ 0 1 2 3 4 5 6 7]
Be=[ 0 0 0 0 0 0 0 0]
elem_shift time:0.000007
reduce_add time:2.231727
Decrypted Result:24
Plaintext Result: 28

Thanks.

**Comment by qianlou** [comment]
Hi, 
Thanks very much for your feedback. Yes, one solution is that you could use the latest code to avoid this "not exact result", but this is a little slower in running time. I just replaced the reduce_add() into seq_add(). 

If you still want to use the old codes, you should take care of the vector length, e.g. 10, you can also get the correct answer using reduce_add(). One of my future works is to get the robust and fast reduce_add().

**Comment by chanfm81** [comment]
Hi,
Thanks for the info.
Looking forward to your future works. Cheers :)
