### ISSUE TITLE
regarding leveled TFHE

### ISSUE THREAD

**Issue by asdfvg123** [qianlou/SHE#6]
I cannot find code regard of leveled TFHE that mentioned in your paper.
It seems like your code used bootstrapping gates such as bootsAND.
Moreover, it seems like TFHE library does not support Leveled TFHE.
Thus, would you give any information of LTFHE?
Thanks.

**Comment by privacylq** [comment]
Thank you for your interest in SHE. Hope these can answer your questions.
In our paper, we listed both levelled- and fully- HE results in tables 4-7. In fully-HE, a bootstrapping operation is performed in every gate; while in levelled-HE, the gate bootstrapping operation is not required. Our currently released source code supports only fully HE. And it is based on the TFHE library of version > 1.0.1. Our code is mainly used to prove that the TFHE shifts and additions are cheaper, and the TFHE ReLUs are  more accurate, which are the contributions in the paper. 
Although TFHE supports both levelled HE and fully HE [1], the TFHE library of version > 1.0.1 does not officially support leveled HE. By the same methodology and parameters in [1], we estimated the latency of each gate, look-up table, automata and circuit bootstrapping in the levelled HE mode. We also have an in-house version of the leveled TFHE based on "experimental-tfhe", but the authors of the TFHE library told us that they will release the leveled code in the near future. So, we originally decided to not release the leveled part until the official leveled TFHE library is released.
If you have any questions, please let me know.

Best,
Qian Lou
[1] Chillotti, Ilaria et al. “Improving TFHE: faster packed homomorphic operations and efficient circuit bootstrapping.” IACR Cryptology ePrint Archive 2017 (2017): 430.
